# Generated by Django 4.0.6 on 2022-11-25 14:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_administrateur', models.BooleanField(default=False, verbose_name='administrateur')),
                ('is_personnel', models.BooleanField(default=False, verbose_name='personnel')),
                ('is_client', models.BooleanField(default=False, verbose_name='client')),
                ('is_avocat', models.BooleanField(default=False, verbose_name='avocat')),
                ('genre', models.CharField(default='pas de genre', max_length=200)),
                ('photo', models.FileField(blank=True, default='aucune image', upload_to='images')),
                ('phone', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.CharField(default='aucune adresse', max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDossier', models.CharField(default='pas de num', max_length=200)),
                ('titreDossier', models.CharField(default='pas de titre', max_length=20)),
                ('objDossier', models.CharField(default='pas d object', max_length=20)),
                ('dateTimeOuverture', models.CharField(default='pas de date', max_length=15)),
                ('dateTimeFermeture', models.CharField(default='pas de date', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomServ', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nationalite', models.CharField(default='pas de nationalite', max_length=200)),
                ('profession', models.CharField(default='aucune profession', max_length=200)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('service', models.CharField(default='pas de service', max_length=50)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('name_client', models.CharField(default='pas de nom', max_length=20)),
                ('fichier', models.FileField(upload_to='media')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDossier', models.CharField(default='pas de num', max_length=200)),
                ('titreDossier', models.CharField(default='pas de titre', max_length=20)),
                ('objDossier', models.CharField(default='pas d object', max_length=20)),
                ('dateTimeOuverture', models.DateTimeField(auto_now_add=True)),
                ('dateTimeFermeture', models.CharField(default='En cours', max_length=100)),
                ('username', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
            },
        ),
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreAct', models.CharField(default='pas de titre', max_length=20)),
                ('DescrpAct', models.TextField(default='pas des actes')),
                ('fichierActe', models.FileField(upload_to='media')),
                ('dateActe', models.DateTimeField(auto_now_add=True)),
                ('numDossier', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cabinet.dossier')),
            ],
            options={
                'verbose_name': 'Acte',
                'verbose_name_plural': 'Actes',
            },
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cabinet.service')),
            ],
            options={
                'verbose_name': 'Avocat',
                'verbose_name_plural': 'Avocats',
            },
        ),
    ]
